apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-internal
  namespace: default  # Change to the desired namespace
spec:
  podSelector: {}  # Selects all pods
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress

